a=int(input("enter the value of a "))
b=int(input("enter the value of b "))
c=(a+b)
d=(a-b)
e=(a/b)
f=(a*b)
print("the sum of two number is :",c)
print("the minus of two number is :",d)
print("the div of two number is :",e)
print("the mul of two number is :",f)